# Generated by Django 4.2.4 on 2024-06-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PO_number', models.CharField(max_length=100)),
                ('item_number', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('qnt', models.IntegerField()),
            ],
        ),
    ]
