# Generated by Django 4.2.4 on 2024-06-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atc', '0002_sales_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='file',
            field=models.FileField(default=None, null=True, upload_to='uploads/'),
        ),
    ]
